##########################
#NOTICE: Modifying these options in this file has no effect. You must put them in SiriProxy's config.yml!
##########################
    
    - name: 'Sabnzbd'
      git: 'git://github.com/mongo527/siriproxy-sabnzbd.git'
      sab_host: '127.0.0.1' # IP of Sabnzbd
      sab_port: '8080' # Port Sabnzbd runs on
      sab_api: '' # Sabnzbd API Key, found at Config > General